import * as fs from 'fs';
import * as path from 'path';
import PDFDocument from 'pdfkit';

/**
 * Generate PDF Report from test results
 */
async function generatePdfReport() {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const outputPath = path.join(__dirname, '../../reports/test-report.pdf');

  // Ensure reports directory exists
  const reportsDir = path.dirname(outputPath);
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  // Pipe to file
  const writeStream = fs.createWriteStream(outputPath);
  doc.pipe(writeStream);

  // Add header
  doc
    .fontSize(24)
    .font('Helvetica-Bold')
    .text('PipelineCraft-R3', { align: 'center' })
    .moveDown(0.5);

  doc
    .fontSize(16)
    .font('Helvetica')
    .text('Automated Test Execution Report', { align: 'center' })
    .moveDown(1);

  // Add metadata
  doc
    .fontSize(10)
    .font('Helvetica')
    .text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' })
    .moveDown(2);

  // Project Information
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('Project Information')
    .moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica')
    .text('Project: PipelineCraft-R3')
    .text('Architecture: Playwright + Cucumber + Screenplay Pattern')
    .text('Testing Framework: TypeScript')
    .text('CI/CD: GitHub Actions')
    .moveDown(1.5);

  // Test Coverage
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('Test Coverage')
    .moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica')
    .text('✓ E2E Tests: SauceDemo Application')
    .text('  - Login functionality (valid and invalid scenarios)')
    .text('  - Product browsing and sorting')
    .text('  - Shopping cart management')
    .text('  - Complete purchase flow')
    .moveDown(0.5);

  doc
    .text('✓ API Tests: DummyJSON API')
    .text('  - Authentication (POST /auth/login, GET /auth/me)')
    .text('  - Products (GET /products, POST /products/add, PUT, DELETE)')
    .text('  - Shopping Cart (POST /carts/add, GET /carts, PUT, DELETE)')
    .text('  - Contract Testing (Schema validation)')
    .text('  - E2E API Flow (Complete user journey)')
    .moveDown(1.5);

  // Test Scenarios
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('BDD Scenarios Covered')
    .moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica')
    .text('1. Purchase Flow (Happy Path)')
    .text('   - Successful purchase of multiple products')
    .text('   - Checkout with valid information')
    .moveDown(0.5);

  doc
    .text('2. Login Failure Scenarios (Negative Testing)')
    .text('   - Invalid username/password')
    .text('   - Locked out user')
    .text('   - Empty credentials')
    .moveDown(0.5);

  doc
    .text('3. Product Sorting')
    .text('   - Sort by name (A-Z, Z-A)')
    .text('   - Sort by price (Low to High, High to Low)')
    .moveDown(1.5);

  // Architecture
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('Screenplay Pattern Architecture')
    .moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica')
    .text('• Actors: ShopperActor, ApiUserActor')
    .text('• Tasks: Login, AddToCart, Checkout, AuthenticateUser, GetProducts, ManageCart')
    .text('• Questions: ApiResponse, PageElement')
    .text('• Interactions: Click, Fill, Navigate, Wait, ApiRequest')
    .moveDown(1.5);

  // Execution Environment
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('Execution Environment')
    .moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica')
    .text(`• Node.js: ${process.version}`)
    .text('• Browsers: Chromium, Firefox, WebKit')
    .text('• CI/CD: GitHub Actions')
    .text('• Report Formats: HTML, JSON, PDF')
    .moveDown(1.5);

  // URLs
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('Test Targets')
    .moveDown(0.5);

  doc
    .fontSize(10)
    .font('Helvetica')
    .text('E2E Application: https://www.saucedemo.com')
    .text('API Endpoint: https://dummyjson.com')
    .text('Repository: https://github.com/willkwolf/PipelineCraft-R3')
    .moveDown(2);

  // Footer
  doc
    .fontSize(8)
    .font('Helvetica')
    .text(
      'This report was automatically generated by PipelineCraft-R3 test automation framework',
      { align: 'center' }
    )
    .text('Powered by Playwright, Cucumber, and TypeScript', { align: 'center' });

  // Finalize PDF
  doc.end();

  return new Promise((resolve, reject) => {
    writeStream.on('finish', () => {
      console.log(`✓ PDF Report generated: ${outputPath}`);
      resolve(outputPath);
    });

    writeStream.on('error', (error) => {
      console.error('Error generating PDF:', error);
      reject(error);
    });
  });
}

// Run if called directly
if (require.main === module) {
  generatePdfReport()
    .then((path) => console.log(`Report saved to: ${path}`))
    .catch((error) => console.error('Failed to generate report:', error));
}

export { generatePdfReport };
